

import 'package:almobtaker/properties.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';

import '../../../routes/app_pages.dart';

 class PrintingTechniquesController extends GetxController{
  //TODO: Implement PasswordResetController
static PrintingTechniquesController get to => Get.find();

List<Autogenerated> list = <Autogenerated>[];
RxInt index = 0.obs;
  @override
  void onInit() {
    super.onInit();


    list.add(Autogenerated(productName: "مجات", type: Type(name: "النوع",types:["سيراميك" , "سحري" ,"عادي"],), shapeProp: null, sizeProp: null));
    list.add(Autogenerated(productName: "ميداليات", type: null, shapeProp: ShapeProp(name: "الشكل", shapes:[ "مربع" ,"دائري"] ) , sizeProp: null));
    list.add(Autogenerated(productName: "مطرات", type: null, shapeProp: null , sizeProp: SizeProp(name: "الحجم", sizes: ["صغير" ,"وسط","كبير"] )));

  }

  @override
  void onReady() {
    super.onReady();
  }

  @override
  void onClose() {
  }






}
