class Autogenerated {
  String? productName;
  Type? type;
  SizeProp? sizeProp;
  ShapeProp? shapeProp;


  Autogenerated(
      {
        this.productName,
        this.shapeProp,
        this.sizeProp,
        this.type
      });
}

class Type{
  String? name;
  List<String>? types;

  Type({this.name, this.types});
}

class ShapeProp{
  String? name;
  List<String>? shapes;

  ShapeProp({this.name, this.shapes});
}

class SizeProp{
  String? name;
  List<String>? sizes;

  SizeProp({this.name, this.sizes});
}



